# Bot Tokens
USER_BOT_TOKEN = '8479377820:AAF8Q-iCPv6juRpRwGtOPHUBAUF8CjFYocY'
BARBER_BOT_TOKEN = '8545396343:AAHHRTPXpLikM0u7WtmbcMxUpmB-GiIXRN4'
ADMIN_BOT_TOKEN = '8546793966:AAHr2IkG8bh9f8_oVgTWv64v9L30dboVSic'

# Admin IDs
ADMIN_IDS = [705457366]  # Add your Telegram ID here

# Database path
DATABASE_PATH = 'barbershop.db'

# Default work hours
DEFAULT_WORK_HOURS = "09:00-19:00"

# Available time slots
TIME_SLOTS = [
    "09:00", "09:30", "10:00", "10:30", "11:00", "11:30",
    "12:00", "12:30", "13:00", "13:30", "14:00", "14:30",
    "15:00", "15:30", "16:00", "16:30", "17:00", "17:30",
    "18:00", "18:30", "19:00"
]

# Language configurations
LANGUAGES = {
    'uz': {
        'language_name': "O'zbekcha",
        'emoji': "🇺🇿",
        'translations': {
            'welcome': "Assalomu alaykum! NavbatGo - sartaroshxona bron qilish botiga xush kelibsiz!\n\n👆 Quyidagi tilni tanlang:",
            'choose_language': "Tilni tanlang:",
            'register_required': "❌ Avval ro'yxatdan o'tishingiz kerak!",
            'send_contact': "📞 Telefon raqamingizni yuboring:",
            'share_contact': "📲 Kontaktni ulashish",
            'cancel': "❌ Bekor qilish",
            'main_menu': "🏠 Asosiy menyu",
            'choose_city': "🏙 Shahar tanlang:",
            'choose_district': "📍 Tuman tanlang:",
            'choose_barbershop': "✂️ Sartaroshxona tanlang:",
            'choose_barber': "💇 Sartarosh tanlang:",
            'choose_service': "💈 Xizmat turini tanlang:",
            'choose_date': "📅 Sana tanlang:",
            'choose_time': "⏰ Vaqt tanlang:",
            'booking_confirmed': "✅ Broningiz tasdiqlandi!",
            'booking_details': "📋 Bron tafsilotlari:",
            'my_bookings': "📒 Mening bronlarim",
            'search': "🔍 Qidirish",
            'nearby': "📍 Yaqin joylar",
            'settings': "⚙️ Sozlamalar",
            'help': "❓ Yordam",
            'back': "🔙 Orqaga",
            'next': "➡️ Keyingisi",
            'confirm': "✅ Tasdiqlash",
            'no_bookings': "📭 Hozircha sizda bronlar mavjud emas",
            'booking_cancelled': "❌ Bron bekor qilindi",
            'today': "Bugun",
            'tomorrow': "Ertaga",
            'experience': "💼 Tajriba",
            'years': "yil",
            'specialty': "🎯 Mutaxassislik",
            'price': "💰 Narxi",
            'duration': "⏱ Davomiylik",
            'rating': "⭐ Reyting",
            'address': "📍 Manzil",
            'phone': "📞 Telefon",
            'description': "📝 Tavsif",
            'work_hours': "🕐 Ish vaqti",
            'reviews': "📝 Sharhlar",
            'write_review': "✍️ Sharh qoldiring",
            'submit': "📤 Yuborish",
            'thank_you': "🙏 Rahmat!",
            'location': "📍 Joylashuv",
            'send_location': "🗺 Joylashuv yuborish",
            'services': "💈 Xizmatlar",
            'minutes': "daqiqa",
            'hour': "soat",
            'before': "oldin",
            'pending': "⏳ Kutilmoqda",
            'confirmed': "✅ Tasdiqlangan",
            'cancelled': "❌ Bekor qilingan",
            'completed': "✅ Yakunlangan",
            'notifications': "🔔 Bildirishnomalar",
            'language': "🌐 Til",
            'profile': "👤 Profil",
            'edit_profile': "✏️ Profilni tahrirlash",
            'change_phone': "📱 Telefon raqamini o'zgartirish",
            'change_name': "👤 Ismni o'zgartirish",
            'logout': "🚪 Chiqish",
            'about': "ℹ️ Bot haqida",
            'contact_us': "📞 Biz bilan bog'lanish",
            'share_bot': "🤖 Botni ulashish",
            'view_on_map': "🗺 Xaritada ko'rish",
            'book_now': "🕒 Hoziroq bron qilish",
            'call_now': "📞 Qo'ng'iroq qilish",
            'website': "🌐 Veb-sayt",
            'instagram': "📸 Instagram",
            'telegram': "✈️ Telegram",
            'loading': "⏳ Yuklanmoqda...",
            'error': "❌ Xatolik yuz berdi",
            'try_again': "🔄 Qayta urinib ko'ring",
            'no_results': "🔍 Hech narsa topilmadi",
            'all': "Barchasi",
            'filter': "🔍 Filtr",
            'sort_by': "📊 Saralash",
            'sort_rating': "⭐ Reyting bo'yicha",
            'sort_price': "💰 Narx bo'yicha",
            'sort_distance': "📍 Masofa bo'yicha",
            'distance': "Masofa",
            'km': "km",
            'open': "🟢 Ochiq",
            'closed': "🔴 Yopiq",
            'popular': "🔥 Mashhur",
            'new': "🆒 Yangi",
            'discount': "🎁 Chegirma",
            'male': "👨 Erkak",
            'female': "👩 Ayol",
            'unisex': "👥 Uniseks",
            'premium': "⭐ Premium",
            'economy': "💰 Iqtisodiy",
            'luxury': "👑 Lux"
        }
    },
    'ru': {
        'language_name': "Русский",
        'emoji': "🇷🇺",
        'translations': {
            'welcome': "Здравствуйте! Добро пожаловать в NavbatGo - бот для бронирования парикмахерских!\n\n👆 Выберите язык ниже:",
            'choose_language': "Выберите язык:",
            'register_required': "❌ Сначала необходимо зарегистрироваться!",
            'send_contact': "📞 Отправьте ваш номер телефона:",
            'share_contact': "📲 Поделиться контактом",
            'cancel': "❌ Отмена",
            'main_menu': "🏠 Главное меню",
            'choose_city': "🏙 Выберите город:",
            'choose_district': "📍 Выберите район:",
            'choose_barbershop': "✂️ Выберите парикмахерскую:",
            'choose_barber': "💇 Выберите парикмахера:",
            'choose_service': "💈 Выберите тип услуги:",
            'choose_date': "📅 Выберите дату:",
            'choose_time': "⏰ Выберите время:",
            'booking_confirmed': "✅ Ваше бронирование подтверждено!",
            'booking_details': "📋 Детали бронирования:",
            'my_bookings': "📒 Мои бронирования",
            'search': "🔍 Поиск",
            'nearby': "📍 Рядом",
            'settings': "⚙️ Настройки",
            'help': "❓ Помощь",
            'back': "🔙 Назад",
            'next': "➡️ Далее",
            'confirm': "✅ Подтвердить",
            'no_bookings': "📭 У вас пока нет бронирований",
            'booking_cancelled': "❌ Бронирование отменено",
            'today': "Сегодня",
            'tomorrow': "Завтра",
            'experience': "💼 Опыт",
            'years': "лет",
            'specialty': "🎯 Специализация",
            'price': "💰 Цена",
            'duration': "⏱ Продолжительность",
            'rating': "⭐ Рейтинг",
            'address': "📍 Адрес",
            'phone': "📞 Телефон",
            'description': "📝 Описание",
            'work_hours': "🕐 Часы работы",
            'reviews': "📝 Отзывы",
            'write_review': "✍️ Оставить отзыв",
            'submit': "📤 Отправить",
            'thank_you': "🙏 Спасибо!",
            'location': "📍 Местоположение",
            'send_location': "🗺 Отправить местоположение",
            'services': "💈 Услуги",
            'minutes': "минут",
            'hour': "час",
            'before': "до",
            'pending': "⏳ Ожидание",
            'confirmed': "✅ Подтверждено",
            'cancelled': "❌ Отменено",
            'completed': "✅ Завершено",
            'notifications': "🔔 Уведомления",
            'language': "🌐 Язык",
            'profile': "👤 Профиль",
            'edit_profile': "✏️ Редактировать профиль",
            'change_phone': "📱 Изменить телефон",
            'change_name': "👤 Изменить имя",
            'logout': "🚪 Выйти",
            'about': "ℹ️ О боте",
            'contact_us': "📞 Связаться с нами",
            'share_bot': "🤖 Поделиться ботом",
            'view_on_map': "🗺 Посмотреть на карте",
            'book_now': "🕒 Забронировать сейчас",
            'call_now': "📞 Позвонить сейчас",
            'website': "🌐 Веб-сайт",
            'instagram': "📸 Instagram",
            'telegram': "✈️ Telegram",
            'loading': "⏳ Загрузка...",
            'error': "❌ Произошла ошибка",
            'try_again': "🔄 Попробуйте снова",
            'no_results': "🔍 Ничего не найдено",
            'all': "Все",
            'filter': "🔍 Фильтр",
            'sort_by': "📊 Сортировать по",
            'sort_rating': "⭐ По рейтингу",
            'sort_price': "💰 По цене",
            'sort_distance': "📍 По расстоянию",
            'distance': "Расстояние",
            'km': "км",
            'open': "🟢 Открыто",
            'closed': "🔴 Закрыто",
            'popular': "🔥 Популярное",
            'new': "🆒 Новое",
            'discount': "🎁 Скидка",
            'male': "👨 Мужское",
            'female': "👩 Женское",
            'unisex': "👥 Унисекс",
            'premium': "⭐ Премиум",
            'economy': "💰 Эконом",
            'luxury': "👑 Люкс"
        }
    },
    'en': {
        'language_name': "English",
        'emoji': "🇺🇸",
        'translations': {
            'welcome': "Hello! Welcome to NavbatGo - barbershop booking bot!\n\n👆 Choose your language below:",
            'choose_language': "Choose language:",
            'register_required': "❌ You need to register first!",
            'send_contact': "📞 Send your phone number:",
            'share_contact': "📲 Share contact",
            'cancel': "❌ Cancel",
            'main_menu': "🏠 Main menu",
            'choose_city': "🏙 Choose city:",
            'choose_district': "📍 Choose district:",
            'choose_barbershop': "✂️ Choose barbershop:",
            'choose_barber': "💇 Choose barber:",
            'choose_service': "💈 Choose service type:",
            'choose_date': "📅 Choose date:",
            'choose_time': "⏰ Choose time:",
            'booking_confirmed': "✅ Your booking is confirmed!",
            'booking_details': "📋 Booking details:",
            'my_bookings': "📒 My bookings",
            'search': "🔍 Search",
            'nearby': "📍 Nearby",
            'settings': "⚙️ Settings",
            'help': "❓ Help",
            'back': "🔙 Back",
            'next': "➡️ Next",
            'confirm': "✅ Confirm",
            'no_bookings': "📭 You have no bookings yet",
            'booking_cancelled': "❌ Booking cancelled",
            'today': "Today",
            'tomorrow': "Tomorrow",
            'experience': "💼 Experience",
            'years': "years",
            'specialty': "🎯 Specialty",
            'price': "💰 Price",
            'duration': "⏱ Duration",
            'rating': "⭐ Rating",
            'address': "📍 Address",
            'phone': "📞 Phone",
            'description': "📝 Description",
            'work_hours': "🕐 Work hours",
            'reviews': "📝 Reviews",
            'write_review': "✍️ Write a review",
            'submit': "📤 Submit",
            'thank_you': "🙏 Thank you!",
            'location': "📍 Location",
            'send_location': "🗺 Send location",
            'services': "💈 Services",
            'minutes': "minutes",
            'hour': "hour",
            'before': "before",
            'pending': "⏳ Pending",
            'confirmed': "✅ Confirmed",
            'cancelled': "❌ Cancelled",
            'completed': "✅ Completed",
            'notifications': "🔔 Notifications",
            'language': "🌐 Language",
            'profile': "👤 Profile",
            'edit_profile': "✏️ Edit profile",
            'change_phone': "📱 Change phone",
            'change_name': "👤 Change name",
            'logout': "🚪 Logout",
            'about': "ℹ️ About",
            'contact_us': "📞 Contact us",
            'share_bot': "🤖 Share bot",
            'view_on_map': "🗺 View on map",
            'book_now': "🕒 Book now",
            'call_now': "📞 Call now",
            'website': "🌐 Website",
            'instagram': "📸 Instagram",
            'telegram': "✈️ Telegram",
            'loading': "⏳ Loading...",
            'error': "❌ An error occurred",
            'try_again': "🔄 Try again",
            'no_results': "🔍 No results found",
            'all': "All",
            'filter': "🔍 Filter",
            'sort_by': "📊 Sort by",
            'sort_rating': "⭐ By rating",
            'sort_price': "💰 By price",
            'sort_distance': "📍 By distance",
            'distance': "Distance",
            'km': "km",
            'open': "🟢 Open",
            'closed': "🔴 Closed",
            'popular': "🔥 Popular",
            'new': "🆒 New",
            'discount': "🎁 Discount",
            'male': "👨 Male",
            'female': "👩 Female",
            'unisex': "👥 Unisex",
            'premium': "⭐ Premium",
            'economy': "💰 Economy",
            'luxury': "👑 Luxury"
        }
    }
}


def get_translation(lang, key):
    """Get translation for specific language and key"""
    if lang not in LANGUAGES:
        lang = 'uz'
    return LANGUAGES[lang]['translations'].get(key, key)
